import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "#/styles/globals.css";
import PageHeader from "#/components/pageHeader";
import PageFooter from "#/components/pageFooter";
import { ThemeProvider } from "../components/theme-provider";
import { Analytics } from "../components/analytics";
import { TailwindIndicator } from "../components/tailwind-indicator";
import { ScrollArea } from "../components/ui/scroll-area";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} overflow-hidden  bg-transparent `}>
        <ThemeProvider attribute="class" defaultTheme="light">
            <PageHeader />
            <ScrollArea className=" rounded-3xl  w-screen  bg-yellow-500 h-screen">
              <main className="flex-1">{children}</main>
            </ScrollArea>
            <PageFooter />
          <Analytics />
          <TailwindIndicator />
        </ThemeProvider>
      </body>
    </html>
  );
}
